services:
  mongo:
    image: mongo:7
    container_name: drop2-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - drop2-mongo-data:/data/db

volumes:
  drop2-mongo-data:
